# Copyright (c) Meta Platforms, Inc. and affiliates.

name: gwil
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - hydra-core=1.1.0
    - POT
    - scipy
